name: svelte-appraize

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    restart: unless-stopped
    environment:
      - ORIGIN=https://appraize.zixian.dev
